generations = 1000
population_count = 250
crossover_probability = 0.5
mutation_probability = 0.05
word_count = 5
use_structure_fitness = true
use_grammar_fitness = true

[word_type_rates]
noun = 0.30
verb = 0.20
adverb = 0.10
adjective = 0.10
preposition = 0.10
determiner = 0.10
conjunction = 0.10

[noun_type_rates]
common = 0.142
proper = 0.142
concrete = 0.142
abstract = 0.142
countable = 0.142
uncountable = 0.142
collective = 0.142

[verb_type_rates]
action = 0.11
transitive = 0.11
intransitive = 0.11
auxiliary = 0.11
linking = 0.11
modal = 0.11
regular = 0.11
irregular = 0.11

[adjective_type_rates]
demonstrative = 0.125
interrogative = 0.125
distributive = 0.125
numeral = 0.125
proper = 0.125
descriptive = 0.125
possessive = 0.125
quantitative = 0.125

[adverb_type_rates]
time = 0.16
frequency = 0.16
place = 0.16
degree = 0.16
manner = 0.16
conjunctive = 0.16

[preposition_type_rates]
place = 0.25
time = 0.25
movement = 0.25
purpose = 0.25

[determiner_type_rates]
article = 0.125
demonstrative = 0.125
distributive = 0.125
interrogative = 0.125
possessive = 0.125
quantifier = 0.125
relative = 0.125
negative = 0.125

[conjunction_type_rates]
coordinating = 0.33
subordinating = 0.33
correlative = 0.33
