generations = 1000
population_count = 250
crossover_probability = 0.5
mutation_probability = 0.05
word_count = 5
use_structure_fitness = true
use_grammar_fitness = true

[word_type_rates]
noun = 0.30
verb = 0.20
adverb = 0.10
adjective = 0.10
preposition = 0.10
determiner = 0.10
conjunction = 0.10

[noun_type_rates]
singular = 0.30
plural = 0.30

[verb_type_rates]
past = 0.30
present = 0.35
future = 0.35

[adjective_type_rates]
demonstrative = 0.125
interrogative = 0.125
distributive = 0.125
numeral = 0.125
proper = 0.125
descriptive = 0.125
possessive = 0.125
quantative = 0.125
