words = [
  #Interrogative
  { word = "what", type = "Interrogative" },
  { word = "which", type = "Interrogative" },
  { word = "whose", type = "Interrogative" },
  { word = "whom", type = "Interrogative" },
  { word = "where", type = "Interrogative" },
  # Distributive
  { word = "each", type = "Distributive" },
  { word = "every", type = "Distributive" },
  { word = "either", type = "Distributive" },
  { word = "neither", type = "Distributive" },
  { word = "all", type = "Distributive" },
  { word = "both", type = "Distributive" },
  { word = "half", type = "Distributive" },
  { word = "quarter", type = "Distributive" },
  { word = "any", type = "Distributive" },
  { word = "some", type = "Distributive" },
  { word = "several", type = "Distributive" },
  { word = "double", type = "Distributive" },
  # Numeral
  { word = "first", type = "Numeral" },
  { word = "second", type = "Numeral" },
  { word = "third", type = "Numeral" },
  { word = "fourth", type = "Numeral" },
  { word = "fifth", type = "Numeral" },
  { word = "last", type = "Numeral" },
  { word = "one", type = "Numeral" },
  { word = "two", type = "Numeral" },
  { word = "three", type = "Numeral" },
  { word = "four", type = "Numeral" },
  { word = "five", type = "Numeral" },
  # Proper
  { word = "American", type = "Proper" },
  { word = "Irish", type = "Proper" },
  { word = "German", type = "Proper" },
  { word = "Polish", type = "Proper" },
  { word = "Chinese", type = "Proper" },
  { word = "Christian", type = "Proper" },
  { word = "Muslim", type = "Proper" },
  { word = "Harvard", type = "Proper" },
  { word = "Canadian", type = "Proper" },
  # Descriptive
  { word = "tasty", type = "Descriptive" },
  { word = "courageous", type = "Descriptive" },
  { word = "short", type = "Descriptive" },
  { word = "angry", type = "Descriptive" },
  { word = "bright", type = "Descriptive" },
  { word = "complex", type = "Descriptive" },
  { word = "smooth", type = "Descriptive" },
  { word = "ancient", type = "Descriptive" },
  { word = "small", type = "Descriptive" },
  { word = "hot", type = "Descriptive" },
  { word = "red", type = "Descriptive" },
  { word = "black", type = "Descriptive" },
  { word = "quiet", type = "Descriptive" },
  { word = "round", type = "Descriptive" },
  # Possessive
  { word = "my", type = "Possessive" },
  { word = "your", type = "Possessive" },
  { word = "his", type = "Possessive" },
  { word = "her", type = "Possessive" },
  { word = "our", type = "Possessive" },
  { word = "their", type = "Possessive" },
  { word = "mine", type = "Possessive" },
  { word = "its", type = "Possessive" },
  # Quantitative
  { word = "many", type = "Quantitative" },
  { word = "few", type = "Quantitative" },
  { word = "some", type = "Quantitative" },
  { word = "several", type = "Quantitative" },
  { word = "any", type = "Quantitative" },
  { word = "more", type = "Quantitative" },
  { word = "less", type = "Quantitative" },
  { word = "enough", type = "Quantitative" },
  { word = "half", type = "Quantitative" },
  { word = "double", type = "Quantitative" },
  { word = "tons", type = "Quantitative" },
  { word = "plenty", type = "Quantitative" },
  { word = "triple", type = "Quantitative" },
  { word = "all", type = "Quantitative" },
  { word = "every", type = "Quantitative" },
  # Demonstrative
  { word = "this", type = "Demonstrative" },
  { word = "that", type = "Demonstrative" },
  { word = "these", type = "Demonstrative" },
  { word = "those", type = "Demonstrative" },
  { word = "such", type = "Demonstrative" },
]
