adjectives = [
  #Interrogative
  { word = "what", adjective_type = "Interrogative" },
  { word = "which", adjective_type = "Interrogative" },
  { word = "whose", adjective_type = "Interrogative" },
  { word = "whom", adjective_type = "Interrogative" },
  { word = "where", adjective_type = "Interrogative" },
  # Distributive
  { word = "each", adjective_type = "Distributive" },
  { word = "every", adjective_type = "Distributive" },
  { word = "either", adjective_type = "Distributive" },
  { word = "neither", adjective_type = "Distributive" },
  { word = "all", adjective_type = "Distributive" },
  { word = "both", adjective_type = "Distributive" },
  { word = "half", adjective_type = "Distributive" },
  { word = "quarter", adjective_type = "Distributive" },
  { word = "any", adjective_type = "Distributive" },
  { word = "some", adjective_type = "Distributive" },
  { word = "several", adjective_type = "Distributive" },
  { word = "double", adjective_type = "Distributive" },
  # Numeral
  { word = "first", adjective_type = "Numeral" },
  { word = "second", adjective_type = "Numeral" },
  { word = "third", adjective_type = "Numeral" },
  { word = "fourth", adjective_type = "Numeral" },
  { word = "fifth", adjective_type = "Numeral" },
  { word = "last", adjective_type = "Numeral" },
  { word = "one", adjective_type = "Numeral" },
  { word = "two", adjective_type = "Numeral" },
  { word = "three", adjective_type = "Numeral" },
  { word = "four", adjective_type = "Numeral" },
  { word = "five", adjective_type = "Numeral" },
  # Proper
  { word = "American", adjective_type = "Proper" },
  { word = "Irish", adjective_type = "Proper" },
  { word = "German", adjective_type = "Proper" },
  { word = "Polish", adjective_type = "Proper" },
  { word = "Chinese", adjective_type = "Proper" },
  { word = "Christian", adjective_type = "Proper" },
  { word = "Muslim", adjective_type = "Proper" },
  { word = "Harvard", adjective_type = "Proper" },
  { word = "Canadian", adjective_type = "Proper" },
  # Descriptive
  { word = "tasty", adjective_type = "Descriptive" },
  { word = "courageous", adjective_type = "Descriptive" },
  { word = "short", adjective_type = "Descriptive" },
  { word = "angry", adjective_type = "Descriptive" },
  { word = "bright", adjective_type = "Descriptive" },
  { word = "complex", adjective_type = "Descriptive" },
  { word = "smooth", adjective_type = "Descriptive" },
  { word = "ancient", adjective_type = "Descriptive" },
  { word = "small", adjective_type = "Descriptive" },
  { word = "hot", adjective_type = "Descriptive" },
  { word = "red", adjective_type = "Descriptive" },
  { word = "black", adjective_type = "Descriptive" },
  { word = "quiet", adjective_type = "Descriptive" },
  { word = "round", adjective_type = "Descriptive" },
  # Possessive
  { word = "my", adjective_type = "Possessive" },
  { word = "your", adjective_type = "Possessive" },
  { word = "his", adjective_type = "Possessive" },
  { word = "her", adjective_type = "Possessive" },
  { word = "our", adjective_type = "Possessive" },
  { word = "their", adjective_type = "Possessive" },
  { word = "mine", adjective_type = "Possessive" },
  { word = "its", adjective_type = "Possessive" },
  # Quantative
  { word = "many", adjective_type = "Quantative" },
  { word = "few", adjective_type = "Quantative" },
  { word = "some", adjective_type = "Quantative" },
  { word = "several", adjective_type = "Quantative" },
  { word = "any", adjective_type = "Quantative" },
  { word = "more", adjective_type = "Quantative" },
  { word = "less", adjective_type = "Quantative" },
  { word = "enough", adjective_type = "Quantative" },
  { word = "half", adjective_type = "Quantative" },
  { word = "double", adjective_type = "Quantative" },
  { word = "tons", adjective_type = "Quantative" },
  { word = "plenty", adjective_type = "Quantative" },
  { word = "triple", adjective_type = "Quantative" },
  { word = "all", adjective_type = "Quantative" },
  { word = "every", adjective_type = "Quantative" },
  # Demonstrative
  { word = "this", adjective_type = "Demonstrative" },
  { word = "that", adjective_type = "Demonstrative" },
  { word = "these", adjective_type = "Demonstrative" },
  { word = "those", adjective_type = "Demonstrative" },
  { word = "such", adjective_type = "Demonstrative" },
]
