nouns = [
  { singular = "cat", plural = "cats", proper = false },
  { singular = "blueberry", plural = "blueberries", proper = false },
  { singular = "sprinkle", plural = "sprinkles", proper = false },
  { singular = "France", proper = true },
  { singular = "dog", plural = "dogs", proper = false },
  { singular = "apple", plural = "apples", proper = false },
  { singular = "river", plural = "rivers", proper = false },
  { singular = "computer", plural = "computers", proper = false },
  { singular = "idea", plural = "ideas", proper = false },
]
