nouns = [
  { word = "cat", quantity = "Singular", proper = false },
  { word = "cats", quantity = "Plural", proper = false },
  { word = "blueberry", quantity = "Singular", proper = false },
  { word = "sprinkle", quantity = "Singular", proper = false },
  { word = "sprinkles", quantity = "Plural", proper = false },
  { word = "France", quantity = "Singular", proper = true },
  { word = "dog", quantity = "Singular", proper = false },
  { word = "dogs", quantity = "Plural", proper = false },
  { word = "apple", quantity = "Singular", proper = false },
  { word = "apples", quantity = "Plural", proper = false },
  { word = "river", quantity = "Singular", proper = false },
  { word = "rivers", quantity = "Plural", proper = false },
  { word = "computer", quantity = "Singular", proper = false },
  { word = "computers", quantity = "Plural", proper = false },
  { word = "idea", quantity = "Singular", proper = false },
  { word = "ideas", quantity = "Plural", proper = false },
]
