words = [
  # Common nouns
  { word = "cat", type = "Common", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "cats", type = "Common", number = "Plural", tangibility = "Concrete", countability = "Countable" },
  { word = "blueberry", type = "Common", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "blueberries", type = "Common", number = "Plural", tangibility = "Concrete", countability = "Countable" },
  { word = "sprinkle", type = "Common", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "sprinkles", type = "Common", number = "Plural", tangibility = "Concrete", countability = "Countable" },
  { word = "dog", type = "Common", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "dogs", type = "Common", number = "Plural", tangibility = "Concrete", countability = "Countable" },
  { word = "apple", type = "Common", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "apples", type = "Common", number = "Plural", tangibility = "Concrete", countability = "Countable" },
  { word = "computer", type = "Common", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "computers", type = "Common", number = "Plural", tangibility = "Concrete", countability = "Countable" },

  # Proper nouns
  { word = "France", type = "Proper", number = "Singular", tangibility = "Concrete", countability = "Uncountable" },
  { word = "Paul", type = "Proper", number = "Singular", tangibility = "Concrete", countability = "Uncountable" },
  { word = "Ireland", type = "Proper", number = "Singular", tangibility = "Concrete", countability = "Uncountable" },
  { word = "Google", type = "Proper", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "Monday", type = "Proper", number = "Singular", tangibility = "Concrete", countability = "Both" },
  { word = "Titanic", type = "Proper", number = "Singular", tangibility = "Concrete", countability = "Countable" },

  # Collective nouns
  { word = "army", type = "Collective", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "band", type = "Collective", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "gang", type = "Collective", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "fleet", type = "Collective", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "crowd", type = "Collective", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "choir", type = "Collective", number = "Singular", tangibility = "Concrete", countability = "Countable" },
  { word = "group", type = "Collective", number = "Singular", tangibility = "Concrete", countability = "Countable" },
]
