nouns = [
  { singular = "cat", plural = "cats" },
  { singular = "blueberry", plural = "blueberries" },
  { singular = "sprinkle", plural = "sprinkles" },
  { singular = "france", proper = true },
  { singular = "dog", plural = "dogs" },
  { singular = "apple", plural = "apples" },
  { singular = "river", plural = "rivers" },
  { singular = "computer", plural = "computers" },
  { singular = "idea", plural = "ideas" },
]
