pronouns = [
  # Subject
  { word = "I", person = "First", quantity = "Singular", pronoun_type = "Subject" },
  { word = "we", person = "First", quantity = "Plural", pronoun_type = "Subject" },
  { word = "you", person = "Second", quantity = "Both", pronoun_type = "Subject" },
  { word = "he", person = "Third", quantity = "Singular", pronoun_type = "Subject" },
  { word = "she", person = "Third", quantity = "Singular", pronoun_type = "Subject" },
  { word = "it", person = "Third", quantity = "Singular", pronoun_type = "Subject" },
  { word = "they", person = "Third", quantity = "Plural", pronoun_type = "Subject" },
  # Object
  { word = "me", person = "First", quantity = "Singular", pronoun_type = "Object" },
  { word = "us", person = "First", quantity = "Plural", pronoun_type = "Object" },
  { word = "you", person = "Second", quantity = "Both", pronoun_type = "Object" },
  { word = "him", person = "Third", quantity = "Singular", pronoun_type = "Object" },
  { word = "her", person = "Third", quantity = "Singular", pronoun_type = "Object" },
  { word = "it", person = "Third", quantity = "Singular", pronoun_type = "Object" },
  { word = "them", person = "Third", quantity = "Plural", pronoun_type = "Object" },
  # Possessive
  { word = "mine", person = "First", quantity = "Singular", pronoun_type = "Possessive" },
  { word = "ours", person = "First", quantity = "Plural", pronoun_type = "Possessive" },
  { word = "yours", person = "Second", quantity = "Both", pronoun_type = "Possessive" },
  { word = "hers", person = "Third", quantity = "Singular", pronoun_type = "Possessive" },
  { word = "his", person = "Third", quantity = "Singular", pronoun_type = "Possessive" },
  { word = "theirs", person = "Third", quantity = "Plural", pronoun_type = "Possessive" },
  # Reflexive
  { word = "myself", person = "First", quantity = "Singular", pronoun_type = "Reflexive" },
  { word = "yourself", person = "Second", quantity = "Singular", pronoun_type = "Reflexive" },
  { word = "himself", person = "Third", quantity = "Singular", pronoun_type = "Reflexive" },
  { word = "herself", person = "Third", quantity = "Singular", pronoun_type = "Reflexive" },
  { word = "itself", person = "Third", quantity = "Singular", pronoun_type = "Reflexive" },
  { word = "ourselves", person = "First", quantity = "Plural", pronoun_type = "Reflexive" },
  { word = "yourselves", person = "Second", quantity = "Plural", pronoun_type = "Reflexive" },
  { word = "themselves", person = "Third", quantity = "Plural", pronoun_type = "Reflexive" },
]
